### ISSUE TITLE
Hotkey not working

### ISSUE THREAD

**Issue by Londmen** [ricochhet/HunterPie.DamageChat#1]
I've tried using the Normal hotkey and a custom one but neither work when i'm in game(in quest). I always start MHW with HunterPie btw.

**Comment by Hideosan500** [comment]
Du you have HunterPie version 1.0.3.97? I had the same problem since the master branch of HunterPie is on 1.0.3.96. You can change to 1.0.3.97 by going to Settings -> General -> Update Branch: BETA in HunterPie itself

**Comment by Londmen** [comment]
> Du you have HunterPie version 1.0.3.97? I had the same problem since the master branch of HunterPie is on 1.0.3.96. You can change to 1.0.3.97 by going to Settings -> General -> Update Branch: BETA in HunterPie itself

I had .96 and updated to the beta now, but it still won't work.

**Comment by ricochhet** [comment]
You'd need to provide more details about your issue.

- Did the plugin load properly, anything in console indicate otherwise?
- Did the console say "Hotkey registered successfully!"
- Do any visible errors occur in the console?
- When in a quest, does pressing the hotkey cause an error?

Alternatively:
- Make sure you have HunterPie version 1.0.3.97 installed, you can change to to this version via Settings -> General -> Update Branch: BETA.
- Disable Windows 10 clipboard history if it's enabled, this has caused issues for some, you can disable it by going to Windows Settings -> System -> Clipboard -> Clipboard History: Toggle this to off.

**Comment by Londmen** [comment]
> You'd need to provide more details about your issue.
> 
> * Did the plugin load properly, anything in console indicate otherwise?
> * Did the console say "Hotkey registered successfully!"
> * Do any visible errors occur in the console?
> * When in a quest, does pressing the hotkey cause an error?
> 
> Alternatively:
> 
> * Make sure you have HunterPie version 1.0.3.97 installed, you can change to to this version via Settings -> General -> Update Branch: BETA.
> * Disable Windows 10 clipboard history if it's enabled, this has caused issues for some, you can disable it by going to Windows Settings -> System -> Clipboard -> Clipboard History: Toggle this to off.

Version is 1.0.3.97 and Clipboard History is disabled.

In the console I can't find any error codes but it does say "0" modules was loaded, when I try to use it in game it's like it's not even installed, no errors or feedback in any way. However I can't see any "Hotkey registered successfully!"

**Comment by ricochhet** [comment]
Then this is not an issue with the plugin itself.

Make sure you have a module.json file under HunterPie/Modules/DamageChat/module.json

Start HunterPie and it should automatically download all additional files. 

I'm not 100% sure whether auto-update is in master branch, but if the plugin does not appear to download additional files, make sure you're on the BETA branch of HunterPie. 

If you switched to BETA and it isn't downloading additional files. Restart your computer, and run HunterPie again, it should properly update to BETA then.

**Comment by Londmen** [comment]
> Then this is not an issue with the plugin itself.
> 
> Make sure you have a module.json file under HunterPie/Modules/DamageChat/module.json
> 
> Start HunterPie and it should automatically download all additional files.
> 
> I'm not 100% sure whether auto-update is in master branch, but if the plugin does not appear to download additional files, make sure you're on the BETA branch of HunterPie.
> 
> If you switched to BETA and it isn't downloading additional files. Restart your computer, and run HunterPie again, it should properly update to BETA then.

Is it suppose to mention the plugin? Like "Loaded 1 module." Cause I can't seem to fix it.

**Comment by ricochhet** [comment]
You're going to have to provide more information about the errors if you want anyone to help you. 

Please copy-paste them and I'll take a look.

**Comment by Londmen** [comment]
I tried moving the file outside it's folder into the main folder and I think that is what caused the errors. Sorry to bother you man, don't think it's too easy to solve this one.
